name: deploy the apps
on:
  repository_dispatch:
    types: [development,staging,production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: helm chart deploy apps
        run: |
          echo "comand helm chart yang akan di jalankan untuk deploy sebagai berikut :"
          echo "helm upgrade ${{ github.event.client_payload.APP_NAME }} ./charts/${{ github.event.client_payload.APP_NAME }}/ --values ./charts/${{ github.event.client_payload.APP_NAME }}/values-${{ github.event.client_payload.environment }}.yml --namespace=test-name-space --install  --set image.version=${{ github.event.client_payload.version }}  --set name.space=test-name-space --wait"

