name: run the workflow
on:
  repository_dispatch:
    types: [my-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print triger details
        run: |
          echo "Jalan Pada repo" ${{ github.event.client_payload.repo }}
          echo "Jalan Pada env" ${{ github.event.client_payload.env }}
