name: run the workflow at ${{ github.event.client_payload.environment }}
on:
  repository_dispatch:
    types: [ ${{ github.event.client_payload.environment }} ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print triger details
        run: |
          echo  ${{ github.event.client_payload.environment }}
          echo  ${{ github.event.client_payload.version }}
